/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreerPartieReseauConfirm.java
 *
 * Created on 31 mai 2012, 09:43:08
 */
package graphique;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import javax.swing.*;
import moteur.Diabolik;

/**
 *
 * @author vernagaa
 */
public class CreerPartieReseauConfirm extends javax.swing.JDialog {

	private static final String err_partie_existante = "Nom déjà existant";
	private static final String err_connexion = "Erreur de communication avec le serveur";
	
	private ListeParties parent;
	private Diabolik diabolik;
	
	public CreerPartieReseauConfirm(Diabolik d, ListeParties parent) {
		super(parent, true);
		diabolik = d;
		this.parent = parent;
		
		initComponents();
		
		// on ferme la boite de dialogue avec appui sur ESC
        AbstractAction act = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                putValue(ACTION_COMMAND_KEY, "actionCommand"); // pas sûr que ce soit utile
                dispose();
            }
        };
        getRootPane().getActionMap().put("esc_quit", act);
        InputMap im = getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        im.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "esc_quit");

        setLocationRelativeTo(getParent());
        setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        annulerButton = new javax.swing.JButton();
        validerButton = new javax.swing.JButton();
        nomPartieTextField = new javax.swing.JTextField();
        erreurLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        classiqueRadioButton = new javax.swing.JRadioButton();
        varianteRadioButton = new javax.swing.JRadioButton();

        buttonGroup.add(classiqueRadioButton);
        buttonGroup.add(varianteRadioButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Créer une partie");
        setMinimumSize(new java.awt.Dimension(0, 110));
        setResizable(false);

        jLabel1.setText("Nom de la partie :");

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        validerButton.setText("Créer");
        validerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerButtonActionPerformed(evt);
            }
        });

        nomPartieTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomPartieTextFieldActionPerformed(evt);
            }
        });

        erreurLabel.setFont(new java.awt.Font("Dialog", 2, 12));
        erreurLabel.setForeground(new java.awt.Color(255, 0, 51));
        erreurLabel.setText("Nom déjà existant");

        jLabel2.setText("Mode de jeu :");

        classiqueRadioButton.setSelected(true);
        classiqueRadioButton.setText("Classique");

        varianteRadioButton.setText("Variante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(170, Short.MAX_VALUE)
                        .addComponent(validerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(annulerButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(classiqueRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(varianteRadioButton))
                            .addComponent(nomPartieTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(erreurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomPartieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(classiqueRadioButton)
                    .addComponent(varianteRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erreurLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annulerButton)
                    .addComponent(validerButton))
                .addContainerGap())
        );

        erreurLabel.setText(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
		dispose();
	}//GEN-LAST:event_annulerButtonActionPerformed

	private void nomPartieTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomPartieTextFieldActionPerformed
		valider();
	}//GEN-LAST:event_nomPartieTextFieldActionPerformed

	private void validerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerButtonActionPerformed
		valider();
	}//GEN-LAST:event_validerButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton classiqueRadioButton;
    private javax.swing.JLabel erreurLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nomPartieTextField;
    private javax.swing.JButton validerButton;
    private javax.swing.JRadioButton varianteRadioButton;
    // End of variables declaration//GEN-END:variables

	private void valider() {
		int confirm = JOptionPane.OK_OPTION;
		
		if(diabolik.getClient().getPartie() != null) {
			confirm = JOptionPane.showConfirmDialog(this,
					"Vous allez être déconnecté de la partie actuelle",
					"Créer une partie",
					JOptionPane.OK_CANCEL_OPTION,
					JOptionPane.WARNING_MESSAGE);
		}
		
		if (confirm == JOptionPane.OK_OPTION) {
			try {
				if (diabolik.creerPartie(nomPartieTextField.getText().trim(), varianteRadioButton.isSelected()) > 0) {
					diabolik.partieEnCours(true);
					dispose();
					parent.setVisible(false);
				} else {
					erreurLabel.setText(err_partie_existante);
				}
			} catch (RemoteException ex) {
				JOptionPane.showMessageDialog(this, err_connexion, "Erreur", JOptionPane.ERROR_MESSAGE);
			}
		}
	}
	
}
