/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package graphique;

import javax.swing.JOptionPane;
import moteur.Diabolik;

/**
 *
 * @author KÃ©vin
 */
public class OptionDePartie extends javax.swing.JDialog {

	/*
	 * Choix cote noir
	 */
	private boolean humainNoirBoolean;
	private boolean ordiDifficleNoir;
	private boolean ordiMoyenNoir;
	private boolean ordiFacileNoir;
	private boolean humainNoirTmp;
	private boolean difficileNoirTmp;
	private boolean moyenNoirTmp;
	private boolean facileNoirTmp;
	/*
	 * Choix cote blanc
	 */
	private boolean humainBlancBoolean;
	private boolean ordiDifficleBlanc;
	private boolean ordiMoyenBlanc;
	private boolean ordiFacileBlanc;
	private boolean humainBlancTmp;
	private boolean difficileBlancTmp;
	private boolean moyenBlancTmp;
	private boolean facileBlancTmp;
	/*
	 * Choix plateau
	 */
	private boolean basique;
	private boolean variante;
	private Diabolik diabolik;

	public OptionDePartie(Diabolik diabolik, FenetrePrincipale parent) {
		super(parent, true);
		this.diabolik = diabolik;

		if (diabolik.getModeDeJeu() == Diabolik.OrdivsOrdi) {
			diabolik.shutdown();
		}

		initComponents();

		assignerValeurBlanc(diabolik.getNiveauIA1());
		assignerValeurNoir(diabolik.getNiveauIA2());

		if (diabolik.isBasique()) {
			basique = true;
			variante = false;
			basiqueSur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/selectionBasique.png")));
			varianteSur.setIcon(null);
		} else {
			basique = false;
			variante = true;
			basiqueSur.setIcon(null);
			varianteSur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/varianteSelection.png")));
		}



		setLocationRelativeTo(getParent());
		setVisible(true);
	}

	private void assignerValeurNoir(int lvl) {
		humainNoirBoolean = false;
		ordiDifficleNoir = false;
		ordiMoyenNoir = false;
		ordiFacileNoir = false;

		survolNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/sansSurvol.png")));

		switch (diabolik.getNiveauIA2()) {
			case 0:
				humainNoirBoolean = true;
				selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/humainSelectionne.png")));
				break;
			case 1:
				ordiFacileNoir = true;
				selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/facileSelectionne.png")));

				break;
			case 2:
				ordiMoyenNoir = true;
				selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/moyenSelection.png")));

				break;
			case 3:
				ordiDifficleNoir = true;
				selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/difficileSelectionne.png")));

				break;
		}
	}

	private void assignerValeurBlanc(int lvl) {
		humainBlancBoolean = false;
		ordiDifficleBlanc = false;
		ordiMoyenBlanc = false;
		ordiFacileBlanc = false;

		survolBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/sansSurvol.png")));


		switch (diabolik.getNiveauIA1()) {
			case 0:
				humainBlancBoolean = true;
				selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/humainSelectionne.png")));
				break;
			case 1:
				ordiFacileBlanc = true;
				selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/facileSelectionne.png")));
				break;
			case 2:
				ordiMoyenBlanc = true;
				selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/moyenSelection.png")));
				break;
			case 3:
				ordiDifficleBlanc = true;
				selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/difficileSelectionne.png")));
				break;
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ordinateurDifficleBlanc = new javax.swing.JLabel();
        humainBlanc = new javax.swing.JLabel();
        ordinateurMoyenBlanc = new javax.swing.JLabel();
        ordinateurFacileBlanc = new javax.swing.JLabel();
        selectionBlanc = new javax.swing.JLabel();
        survolBlanc = new javax.swing.JLabel();
        ordinateurFacileNoir = new javax.swing.JLabel();
        ordinateurMoyenNoir = new javax.swing.JLabel();
        humainNoir = new javax.swing.JLabel();
        ordinateurDifficleNoir = new javax.swing.JLabel();
        selectionNoir = new javax.swing.JLabel();
        survolNoir = new javax.swing.JLabel();
        annullerJbutton = new javax.swing.JButton();
        validerButton = new javax.swing.JButton();
        varianteSur = new javax.swing.JLabel();
        basiqueSur = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuration de la partie");
        setMinimumSize(new java.awt.Dimension(400, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        ordinateurDifficleBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/ordinateurDifficile.png"))); // NOI18N
        ordinateurDifficleBlanc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ordinateurDifficleBlanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordinateurDifficleBlancMouseClicked(evt);
            }
        });
        ordinateurDifficleBlanc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ordinateurDifficleBlancMouseMoved(evt);
            }
        });
        getContentPane().add(ordinateurDifficleBlanc);
        ordinateurDifficleBlanc.setBounds(30, 160, 130, 20);

        humainBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/humain.png"))); // NOI18N
        humainBlanc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        humainBlanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                humainBlancMouseClicked(evt);
            }
        });
        humainBlanc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                humainBlancMouseMoved(evt);
            }
        });
        getContentPane().add(humainBlanc);
        humainBlanc.setBounds(30, 60, 128, 30);

        ordinateurMoyenBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/ordinateurMoyen.png"))); // NOI18N
        ordinateurMoyenBlanc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ordinateurMoyenBlanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordinateurMoyenBlancMouseClicked(evt);
            }
        });
        ordinateurMoyenBlanc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ordinateurMoyenBlancMouseMoved(evt);
            }
        });
        getContentPane().add(ordinateurMoyenBlanc);
        ordinateurMoyenBlanc.setBounds(30, 130, 130, 22);

        ordinateurFacileBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/ordinateurFacile.png"))); // NOI18N
        ordinateurFacileBlanc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ordinateurFacileBlanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordinateurFacileBlancMouseClicked(evt);
            }
        });
        ordinateurFacileBlanc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ordinateurFacileBlancMouseMoved(evt);
            }
        });
        getContentPane().add(ordinateurFacileBlanc);
        ordinateurFacileBlanc.setBounds(30, 92, 130, 30);

        selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/humainSelectionne.png"))); // NOI18N
        selectionBlanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectionBlancMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selectionBlancMouseExited(evt);
            }
        });
        getContentPane().add(selectionBlanc);
        selectionBlanc.setBounds(10, 20, 170, 170);
        getContentPane().add(survolBlanc);
        survolBlanc.setBounds(10, 20, 170, 170);

        ordinateurFacileNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/ordinateurFacile.png"))); // NOI18N
        ordinateurFacileNoir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ordinateurFacileNoir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordinateurFacileNoirMouseClicked(evt);
            }
        });
        ordinateurFacileNoir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ordinateurFacileNoirMouseMoved(evt);
            }
        });
        getContentPane().add(ordinateurFacileNoir);
        ordinateurFacileNoir.setBounds(240, 92, 130, 30);

        ordinateurMoyenNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/ordinateurMoyen.png"))); // NOI18N
        ordinateurMoyenNoir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ordinateurMoyenNoir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordinateurMoyenNoirMouseClicked(evt);
            }
        });
        ordinateurMoyenNoir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ordinateurMoyenNoirMouseMoved(evt);
            }
        });
        getContentPane().add(ordinateurMoyenNoir);
        ordinateurMoyenNoir.setBounds(240, 130, 130, 22);

        humainNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/humain.png"))); // NOI18N
        humainNoir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        humainNoir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                humainNoirMouseClicked(evt);
            }
        });
        humainNoir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                humainNoirMouseMoved(evt);
            }
        });
        getContentPane().add(humainNoir);
        humainNoir.setBounds(240, 60, 128, 30);

        ordinateurDifficleNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/ordinateurDifficile.png"))); // NOI18N
        ordinateurDifficleNoir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ordinateurDifficleNoir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordinateurDifficleNoirMouseClicked(evt);
            }
        });
        ordinateurDifficleNoir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ordinateurDifficleNoirMouseMoved(evt);
            }
        });
        getContentPane().add(ordinateurDifficleNoir);
        ordinateurDifficleNoir.setBounds(240, 160, 130, 20);

        selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/humainSelectionne.png"))); // NOI18N
        selectionNoir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectionNoirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selectionNoirMouseExited(evt);
            }
        });
        getContentPane().add(selectionNoir);
        selectionNoir.setBounds(220, 20, 170, 170);
        getContentPane().add(survolNoir);
        survolNoir.setBounds(220, 20, 170, 170);

        annullerJbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/annuler.png"))); // NOI18N
        annullerJbutton.setBorder(null);
        annullerJbutton.setBorderPainted(false);
        annullerJbutton.setContentAreaFilled(false);
        annullerJbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        annullerJbutton.setFocusPainted(false);
        annullerJbutton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/annulerClique.png"))); // NOI18N
        annullerJbutton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/annulerSurvol.png"))); // NOI18N
        annullerJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullerJbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(annullerJbutton);
        annullerJbutton.setBounds(210, 440, 100, 50);

        validerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/valider.png"))); // NOI18N
        validerButton.setBorder(null);
        validerButton.setBorderPainted(false);
        validerButton.setContentAreaFilled(false);
        validerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        validerButton.setDefaultCapable(false);
        validerButton.setFocusPainted(false);
        validerButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/validerClique.png"))); // NOI18N
        validerButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/validerSurvol.png"))); // NOI18N
        validerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(validerButton);
        validerButton.setBounds(100, 440, 100, 50);

        varianteSur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/varianteSelection.png"))); // NOI18N
        varianteSur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        varianteSur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varianteSurMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                varianteSurMouseExited(evt);
            }
        });
        varianteSur.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                varianteSurMouseMoved(evt);
            }
        });
        getContentPane().add(varianteSur);
        varianteSur.setBounds(200, 230, 180, 210);

        basiqueSur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/selectionBasique.png"))); // NOI18N
        basiqueSur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        basiqueSur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                basiqueSurMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                basiqueSurMouseExited(evt);
            }
        });
        basiqueSur.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                basiqueSurMouseMoved(evt);
            }
        });
        getContentPane().add(basiqueSur);
        basiqueSur.setBounds(30, 230, 180, 210);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/fondOptionPartie.png"))); // NOI18N
        getContentPane().add(fond);
        fond.setBounds(0, 0, 400, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void ordinateurDifficleBlancMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordinateurDifficleBlancMouseClicked
		selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/difficileSelectionne.png")));
		humainBlancBoolean = false;
		ordiFacileBlanc = false;
		ordiMoyenBlanc = false;
		ordiDifficleBlanc = true;
	}//GEN-LAST:event_ordinateurDifficleBlancMouseClicked

	private void ordinateurDifficleBlancMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordinateurDifficleBlancMouseMoved
		survolBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/difficileSelectionneSurvol.png")));
		humainBlancTmp = false;
		difficileBlancTmp = true;
		moyenBlancTmp = false;
		facileBlancTmp = false;
	}//GEN-LAST:event_ordinateurDifficleBlancMouseMoved

	private void humainBlancMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_humainBlancMouseClicked
		selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/humainSelectionne.png")));
		humainBlancBoolean = true;
		ordiFacileBlanc = false;
		ordiMoyenBlanc = false;
		ordiDifficleBlanc = false;
	}//GEN-LAST:event_humainBlancMouseClicked

	private void humainBlancMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_humainBlancMouseMoved
		survolBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/humainSurvol.png")));
		humainBlancTmp = true;
		difficileBlancTmp = false;
		moyenBlancTmp = false;
		facileBlancTmp = false;
	}//GEN-LAST:event_humainBlancMouseMoved

	private void ordinateurMoyenBlancMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordinateurMoyenBlancMouseClicked
		selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/moyenSelection.png")));
		humainBlancBoolean = false;
		ordiFacileBlanc = false;
		ordiMoyenBlanc = true;
		ordiDifficleBlanc = false;
	}//GEN-LAST:event_ordinateurMoyenBlancMouseClicked

	private void ordinateurMoyenBlancMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordinateurMoyenBlancMouseMoved
		survolBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/moyenSelectionSurvol.png")));
		humainBlancTmp = false;
		difficileBlancTmp = false;
		moyenBlancTmp = true;
		facileBlancTmp = false;
	}//GEN-LAST:event_ordinateurMoyenBlancMouseMoved

	private void ordinateurFacileBlancMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordinateurFacileBlancMouseClicked
		selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/facileSelectionne.png")));
		humainBlancBoolean = false;
		ordiFacileBlanc = true;
		ordiMoyenBlanc = false;
		ordiDifficleBlanc = false;
	}//GEN-LAST:event_ordinateurFacileBlancMouseClicked

	private void ordinateurFacileBlancMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordinateurFacileBlancMouseMoved
		survolBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/facileSurvol.png")));
		humainBlancTmp = false;
		difficileBlancTmp = false;
		moyenBlancTmp = false;
		facileBlancTmp = true;
	}//GEN-LAST:event_ordinateurFacileBlancMouseMoved

	private void validerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerButtonActionPerformed
		String j = "adversaire";
		int confirm = JOptionPane.showConfirmDialog(diabolik.getFenetrePrincipale(),
				"Voulez-vous quitter cette partie et donner la victoire au joueur " + j + "?",
				"Nouvelle partie",
				JOptionPane.YES_NO_OPTION);
		if (confirm == JOptionPane.YES_OPTION) {
			if (humainBlancBoolean && humainNoirBoolean) {
				diabolik.setModeDeJeu(0);
			} else if (humainBlancBoolean && !humainNoirBoolean) {
				diabolik.setModeDeJeu(1);
			} else if (!humainBlancBoolean && humainNoirBoolean) {
				diabolik.setModeDeJeu(3);
			} else {
				diabolik.setModeDeJeu(2);
			}

			if (humainNoirBoolean) {
				diabolik.setNiveauIA2(0);
			} else if (ordiFacileNoir) {
				diabolik.setNiveauIA2(1);
			} else if (ordiMoyenNoir) {
				diabolik.setNiveauIA2(2);
			} else {
				diabolik.setNiveauIA2(3);
			}

			if (humainBlancBoolean) {
				diabolik.setNiveauIA1(0);
			} else if (ordiFacileBlanc) {
				diabolik.setNiveauIA1(1);
			} else if (ordiMoyenBlanc) {
				diabolik.setNiveauIA1(2);
			} else {
				diabolik.setNiveauIA1(3);
			}

			if (basique) {
				diabolik.setBasique(true);
			} else {
				diabolik.setBasique(false);
			}

			diabolik.nouvellePartie();
			dispose();
		}
	}//GEN-LAST:event_validerButtonActionPerformed

	private void annullerJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullerJbuttonActionPerformed
		dispose();
	}//GEN-LAST:event_annullerJbuttonActionPerformed

	private void selectionBlancMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectionBlancMouseClicked
		if (humainBlancTmp) {
			selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/humainSelectionne.png")));
			humainBlancBoolean = true;
			ordiFacileBlanc = false;
			ordiMoyenBlanc = false;
			ordiDifficleBlanc = false;
		} else if (facileBlancTmp) {
			selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/facileSelectionne.png")));
			humainBlancBoolean = false;
			ordiFacileBlanc = true;
			ordiMoyenBlanc = false;
			ordiDifficleBlanc = false;
		} else if (moyenBlancTmp) {
			selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/moyenSelection.png")));
			humainBlancBoolean = false;
			ordiFacileBlanc = false;
			ordiMoyenBlanc = true;
			ordiDifficleBlanc = false;
		} else if (difficileBlancTmp) {
			selectionBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/difficileSelectionne.png")));
			humainBlancBoolean = false;
			ordiFacileBlanc = false;
			ordiMoyenBlanc = false;
			ordiDifficleBlanc = true;
		}
	}//GEN-LAST:event_selectionBlancMouseClicked

	private void selectionBlancMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectionBlancMouseExited
		survolBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/sansSurvol.png")));
	}//GEN-LAST:event_selectionBlancMouseExited

	private void selectionNoirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectionNoirMouseClicked
		if (humainNoirTmp) {
			selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/humainSelectionne.png")));
			humainNoirBoolean = true;
			ordiFacileNoir = false;
			ordiMoyenNoir = false;
			ordiDifficleNoir = false;
		} else if (facileNoirTmp) {
			selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/facileSelectionne.png")));
			humainNoirBoolean = false;
			ordiFacileNoir = true;
			ordiMoyenNoir = false;
			ordiDifficleNoir = false;
		} else if (moyenNoirTmp) {
			selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/moyenSelection.png")));
			humainNoirBoolean = false;
			ordiFacileNoir = false;
			ordiMoyenNoir = true;
			ordiDifficleNoir = false;
		} else if (difficileNoirTmp) {
			selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/difficileSelectionne.png")));
			humainNoirBoolean = false;
			ordiFacileNoir = false;
			ordiMoyenNoir = false;
			ordiDifficleNoir = true;
		}
	}//GEN-LAST:event_selectionNoirMouseClicked

	private void selectionNoirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectionNoirMouseExited
		survolNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/sansSurvol.png")));
	}//GEN-LAST:event_selectionNoirMouseExited

	private void ordinateurFacileNoirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordinateurFacileNoirMouseClicked
		selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/facileSelectionne.png")));
		humainNoirBoolean = false;
		ordiFacileNoir = true;
		ordiMoyenNoir = false;
		ordiDifficleNoir = false;
	}//GEN-LAST:event_ordinateurFacileNoirMouseClicked

	private void ordinateurFacileNoirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordinateurFacileNoirMouseMoved
		survolNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/facileSurvol.png")));
		humainNoirTmp = false;
		difficileNoirTmp = false;
		moyenNoirTmp = false;
		facileNoirTmp = true;
	}//GEN-LAST:event_ordinateurFacileNoirMouseMoved

	private void ordinateurMoyenNoirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordinateurMoyenNoirMouseClicked
		selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/moyenSelection.png")));
		humainNoirBoolean = false;
		ordiFacileNoir = false;
		ordiMoyenNoir = true;
		ordiDifficleNoir = false;
	}//GEN-LAST:event_ordinateurMoyenNoirMouseClicked

	private void ordinateurMoyenNoirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordinateurMoyenNoirMouseMoved
		survolNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/moyenSelectionSurvol.png")));
		humainNoirTmp = false;
		difficileNoirTmp = false;
		moyenNoirTmp = true;
		facileNoirTmp = false;
	}//GEN-LAST:event_ordinateurMoyenNoirMouseMoved

	private void humainNoirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_humainNoirMouseClicked
		selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/humainSelectionne.png")));
		humainNoirBoolean = true;
		ordiFacileNoir = false;
		ordiMoyenNoir = false;
		ordiDifficleNoir = false;
	}//GEN-LAST:event_humainNoirMouseClicked

	private void humainNoirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_humainNoirMouseMoved
		survolNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/humainSurvol.png")));
		humainNoirTmp = true;
		difficileNoirTmp = false;
		moyenNoirTmp = false;
		facileNoirTmp = false;
	}//GEN-LAST:event_humainNoirMouseMoved

	private void ordinateurDifficleNoirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordinateurDifficleNoirMouseClicked
		selectionNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/difficileSelectionne.png")));
		humainNoirBoolean = false;
		ordiFacileNoir = false;
		ordiMoyenNoir = false;
		ordiDifficleNoir = true;
	}//GEN-LAST:event_ordinateurDifficleNoirMouseClicked

	private void ordinateurDifficleNoirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordinateurDifficleNoirMouseMoved
		survolNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/difficileSelectionneSurvol.png")));
		humainNoirTmp = false;
		difficileNoirTmp = true;
		moyenNoirTmp = false;
		facileNoirTmp = false;
	}//GEN-LAST:event_ordinateurDifficleNoirMouseMoved

	private void varianteSurMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varianteSurMouseMoved
		if (!variante) {
			varianteSur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/varianteSurvol.png")));
		}
	}//GEN-LAST:event_varianteSurMouseMoved

	private void varianteSurMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varianteSurMouseExited
		if (!variante) {
			varianteSur.setIcon(null);
		}
	}//GEN-LAST:event_varianteSurMouseExited

	private void varianteSurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varianteSurMouseClicked
		variante = true;
		basique = false;
		varianteSur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/varianteSelection.png")));
		basiqueSur.setIcon(null);
	}//GEN-LAST:event_varianteSurMouseClicked

	private void basiqueSurMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basiqueSurMouseMoved
		if (!basique) {
			basiqueSur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/survolBasique.png")));
		}
	}//GEN-LAST:event_basiqueSurMouseMoved

	private void basiqueSurMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basiqueSurMouseExited
		if (!basique) {
			basiqueSur.setIcon(null);
		}
	}//GEN-LAST:event_basiqueSurMouseExited

	private void basiqueSurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basiqueSurMouseClicked
		variante = false;
		basique = true;
		basiqueSur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/secondeVersion/fenetreConfiguration/selectionBasique.png")));
		varianteSur.setIcon(null);
	}//GEN-LAST:event_basiqueSurMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annullerJbutton;
    private javax.swing.JLabel basiqueSur;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel humainBlanc;
    private javax.swing.JLabel humainNoir;
    private javax.swing.JLabel ordinateurDifficleBlanc;
    private javax.swing.JLabel ordinateurDifficleNoir;
    private javax.swing.JLabel ordinateurFacileBlanc;
    private javax.swing.JLabel ordinateurFacileNoir;
    private javax.swing.JLabel ordinateurMoyenBlanc;
    private javax.swing.JLabel ordinateurMoyenNoir;
    private javax.swing.JLabel selectionBlanc;
    private javax.swing.JLabel selectionNoir;
    private javax.swing.JLabel survolBlanc;
    private javax.swing.JLabel survolNoir;
    private javax.swing.JButton validerButton;
    javax.swing.JLabel varianteSur;
    // End of variables declaration//GEN-END:variables
}
